In [2]:
import numpy as np

#**Zadanie 1**

In [4]:
a = np.array([1,4,3,5,3])
print(a)

[1 4 3 5 3]


In [8]:
#bez inta

In [9]:
b = np.array([3.14,4,2,3])
print(b)

[3.14 4.   2.   3.  ]


In [10]:
#int32

In [11]:
b = np.array([3.14, 4, 2, 3],dtype=int)
b

array([3, 4, 2, 3])

In [15]:
c=np.array([[2,4,6],[1,2,3]])
print(c)

[[2 4 6]
 [1 2 3]]


In [16]:
d=np.array([[-3.,2.3],[0.1,5.0],[8.0,11.0]])
print(d)

[[-3.   2.3]
 [ 0.1  5. ]
 [ 8.  11. ]]


In [18]:
e=np.array([[[2,4],[1,2],[8,9]],[[7,6],[-3,4],[0,8]]])
print(e)

[[[ 2  4]
  [ 1  2]
  [ 8  9]]

 [[ 7  6]
  [-3  4]
  [ 0  8]]]


#**Zadanie 2**

In [19]:
a.ndim,b.ndim,c.ndim,d.ndim,e.ndim

(1, 1, 2, 2, 3)

In [22]:
a.shape,b.shape,c.shape,d.shape,e.shape

((5,), (4,), (2, 3), (3, 2), (2, 3, 2))

In [23]:
a.size, b.size,c.size,d.size,e.size

(5, 4, 6, 6, 12)

In [24]:
a.dtype,b.dtype,c.dtype,d.dtype,e.dtype

(dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('float64'),
 dtype('int64'))

In [25]:
a.itemsize,b.itemsize,c.itemsize,d.itemsize,e.itemsize

(8, 8, 8, 8, 8)

In [26]:
a.nbytes,b.nbytes,c.nbytes,d.nbytes,e.nbytes

(40, 32, 48, 48, 96)

#**Zadanie 3**

In [38]:
X1 = np.random.random((3,2,4))

X2 = np.zeros((2,3))

X3 = np.full((6,2,1,2),7)

X4 = np.random.randint(2,20,(5,7))

X5 = np.ones((5,5))

In [39]:
X1

array([[[0.4070197 , 0.98621055, 0.55478561, 0.59196399],
        [0.41822612, 0.17290574, 0.40443101, 0.44210796]],

       [[0.74761571, 0.74483672, 0.51288445, 0.44470622],
        [0.48961532, 0.37642474, 0.46962324, 0.90785141]],

       [[0.76639296, 0.79823238, 0.45462832, 0.20843041],
        [0.20183244, 0.29177744, 0.95884464, 0.89156037]]])

In [40]:
X2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
X3

array([[[[7, 7]],

        [[7, 7]]],


       [[[7, 7]],

        [[7, 7]]],


       [[[7, 7]],

        [[7, 7]]],


       [[[7, 7]],

        [[7, 7]]],


       [[[7, 7]],

        [[7, 7]]],


       [[[7, 7]],

        [[7, 7]]]])

In [42]:
X4

array([[19, 10,  8,  9, 17, 15, 18],
       [19,  9, 15, 17,  8,  2,  2],
       [ 6, 10, 11,  2,  6,  8, 19],
       [14,  8, 17,  8, 13,  9,  9],
       [18, 16, 10,  4,  8,  3, 19]])

In [43]:
X5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
X4[1,2]

15

In [52]:
X4[2,:]

array([ 6, 10, 11,  2,  6,  8, 19])

In [53]:
X5[:,2]

array([1., 1., 1., 1., 1.])

#**Zadanie 4**

In [74]:
A = np.random.randint(0,10,(4,5))
A

array([[2, 7, 3, 0, 4],
       [8, 4, 3, 4, 9],
       [0, 8, 6, 4, 1],
       [3, 3, 2, 7, 6]])

In [75]:
B = A[:,1:3]
B

array([[7, 3],
       [4, 3],
       [8, 6],
       [3, 2]])

In [76]:
C = A[1:3,1:5]
C

array([[4, 3, 4, 9],
       [8, 6, 4, 1]])

In [83]:
B =B * 2

In [84]:
B

array([[28, 12],
       [16, 12],
       [32, 24],
       [12,  8]])

In [85]:
A

array([[2, 7, 3, 0, 4],
       [8, 4, 3, 4, 9],
       [0, 8, 6, 4, 1],
       [3, 3, 2, 7, 6]])

In [86]:
C

array([[4, 3, 4, 9],
       [8, 6, 4, 1]])

In [87]:
B1 = A[:,1:3].copy()
B1

array([[7, 3],
       [4, 3],
       [8, 6],
       [3, 2]])

In [88]:
C1 = A[1:3,1:5].copy()
C1

array([[4, 3, 4, 9],
       [8, 6, 4, 1]])

#**Zadanie 5**

In [135]:
D = np.array(np.arange(0,12))
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [136]:
D.shape

(12,)

In [137]:
D1=D.reshape(6,2)
print(D1)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [138]:
D2=D.reshape(3,2,2)
print(D2)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [139]:
D3=D.reshape(6,2,1)
print(D3)

[[[ 0]
  [ 1]]

 [[ 2]
  [ 3]]

 [[ 4]
  [ 5]]

 [[ 6]
  [ 7]]

 [[ 8]
  [ 9]]

 [[10]
  [11]]]


In [140]:
D4=D.reshape(1, 2, 6)
print(D4)



[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]]


In [141]:
D5=D.reshape(1, 6, 2)
print(D5)


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]]


In [142]:
D6=D.reshape(2, 1, 6)
print(D6)


[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]]


In [143]:
D7=D.reshape(2, 6, 1)
print(D7)


[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]]


In [144]:
D8=D.reshape(6, 1, 2)
print(D8)


[[[ 0  1]]

 [[ 2  3]]

 [[ 4  5]]

 [[ 6  7]]

 [[ 8  9]]

 [[10 11]]]


In [145]:
D9=D.reshape(1, 3, 4)
print(D9)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [146]:
D10=D.reshape(1, 4, 3)
print(D10)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


In [147]:
D11=D.reshape(3, 1, 4)
print(D11)


[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [148]:
D12=D.reshape(3, 4, 1)
print(D12)


[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]


In [149]:
D13=D.reshape(4, 1, 3)
print(D13)


[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]


In [150]:
D14=D.reshape(4, 3, 1)
print(D14)


[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]


In [151]:
D15=D.reshape(2, 2, 3)
print(D15)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [152]:
D16=D.reshape(2, 3, 2)
print(D16)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


#**Zadanie 6**

In [154]:
c = np.array([[2,4],[1,2]])
d = np.array([[-3,5],[-7,8]])


print("c=\n",c)
print("d=\n",d)
print("c.shape=",c.shape)
print("d.shape=",d.shape)
print(np.concatenate([c,d],axis=0))
print(np.concatenate([c,d],axis=1))
print(np.concatenate([d,c],axis=0))
print(np.concatenate([d,c],axis=1))

c=
 [[2 4]
 [1 2]]
d=
 [[-3  5]
 [-7  8]]
c.shape= (2, 2)
d.shape= (2, 2)
[[ 2  4]
 [ 1  2]
 [-3  5]
 [-7  8]]
[[ 2  4 -3  5]
 [ 1  2 -7  8]]
[[-3  5]
 [-7  8]
 [ 2  4]
 [ 1  2]]
[[-3  5  2  4]
 [-7  8  1  2]]


In [164]:
print("c=\n",c)
print("X2=\n",X2)
print("c.shape=",c.shape)
print("X2.shape=",X2.shape)
#print(np.concatenate([c,X2],axis=0)) nie da się
#print(np.concatenate([c,X2],axis=1)) nie da się
#print(np.concatenate([X2,c],axis=0)) nie da się
print(np.concatenate([X2,c],axis=1))



c=
 [[2 4]
 [1 2]]
X2=
 [[0. 0. 0.]
 [0. 0. 0.]]
c.shape= (2, 2)
X2.shape= (2, 3)
[[0. 0. 0. 2. 4.]
 [0. 0. 0. 1. 2.]]


In [192]:
print("X1=\n",X1)
print("X2=\n",X2)
print("X1.shape=",X1.shape)
print("X2.shape=",X2.shape)
#print(np.concatenate([X1,X2],axis=0)) #nie da się bez reshape()ale reshape nie możliwy
#print(np.concatenate([X1,X2],axis=1)) #nie da się bez reshape() ale reshape nie możliwy
#print(np.concatenate([X2,X1],axis=0)) #nie da się bez reshape()ale reshape nie możliwy
#print(np.concatenate([X2,X1],axis=1)) #nie da się bez reshape() ale reshape nie możliwy


X1=
 [[[0.4070197  0.98621055 0.55478561 0.59196399]
  [0.41822612 0.17290574 0.40443101 0.44210796]]

 [[0.74761571 0.74483672 0.51288445 0.44470622]
  [0.48961532 0.37642474 0.46962324 0.90785141]]

 [[0.76639296 0.79823238 0.45462832 0.20843041]
  [0.20183244 0.29177744 0.95884464 0.89156037]]]
X2=
 [[0. 0. 0.]
 [0. 0. 0.]]
X1.shape= (3, 2, 4)
X2.shape= (2, 3)


In [189]:
print("D11=\n",D11)
print("D13=\n",D13)
print("D11.shape=",D11.shape)
print("D13.shape=",D13.shape)
#print(np.concatenate([D11,D13],axis=0)) nie da się bez reshape()
#print(np.concatenate([D11,D13],axis=1)) nie da się bez reshape()
#print(np.concatenate([D13,D11],axis=0)) nie da się bez reshape()
#print(np.concatenate([D13,D11],axis=1)) nie da się bez reshape()
D13d=D13.reshape(D11.shape)
print(np.concatenate([D11,D13d],axis=0))
print(np.concatenate([D11,D13d],axis=1))
print(np.concatenate([D13d,D11],axis=0))
print(np.concatenate([D13d,D11],axis=1))


D11=
 [[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
D13=
 [[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]
D11.shape= (3, 1, 4)
D13.shape= (4, 1, 3)
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]

 [[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]]]
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]

 [[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]]]


#**Zadanie 7**


In [118]:
c*d

array([[-6, 20],
       [-7, 16]])

In [119]:
d+6
d



array([[-3,  5],
       [-7,  8]])

In [120]:
d*8
d


array([[-3,  5],
       [-7,  8]])

In [121]:
d-8
d


array([[-3,  5],
       [-7,  8]])

In [122]:
d/8
d


array([[-3,  5],
       [-7,  8]])

In [123]:
abs(8)
d


array([[-3,  5],
       [-7,  8]])

In [124]:
np.exp(d)
d


array([[-3,  5],
       [-7,  8]])

In [125]:
np.power(d,4)
d

array([[-3,  5],
       [-7,  8]])

In [126]:
A = np.array([[1],[1]])
A

array([[1],
       [1]])

In [127]:
A = A+X2
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [128]:
A = A-X2
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [129]:
A = A*X2
A

array([[0., 0., 0.],
       [0., 0., 0.]])

#**Zadadnie 8**

In [130]:
c = np.array([[1,1,1],[1,1,1]])
d = np.array([[0,1,2]])

c+d



array([[1, 2, 3],
       [1, 2, 3]])

In [131]:
c= np.array([[0],[1],[2]])
d = np.array([[0,1,2]])
c+d

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])